# Generated by Django 3.2.25 on 2026-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
    ]
