# Generated by Django 3.2.25 on 2026-02-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('item_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('store', models.CharField(blank=True, max_length=100)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='receipts.receipt')),
            ],
        ),
    ]
