# Generated by Django 3.2.25 on 2026-02-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('item_type', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
