# Generated by Django 3.2.25 on 2026-02-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('items', '0002_auto_20260224_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceiptItem',
            new_name='Item',
        ),
    ]
