# Generated by Django 3.2.25 on 2026-02-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_receiptitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='line_subtotal',
        ),
    ]
