# Generated by Django 3.2.25 on 2026-02-17 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('gbp', 'GBP')], default='eur', max_length=3)),
                ('store_name', models.CharField(blank=True, max_length=150)),
                ('store_address', models.CharField(blank=True, max_length=255)),
                ('date_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, max_length=80)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('items_text', models.TextField(blank=True)),
                ('return_by_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounts.user')),
            ],
        ),
    ]
