# Generated by Django 3.2.25 on 2026-02-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('raw_html', models.TextField(blank=True, default='')),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='receipts.receipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['message_id'], name='receipts_em_message_428381_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['is_processed'], name='receipts_em_is_proc_e9ee72_idx'),
        ),
    ]
