# Generated by Django 3.2.25 on 2026-02-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20260224_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='processing_error',
        ),
    ]
